### Rota para listar produtos

GET http://localhost:3000/
Content-Type: application/json

###

### salvar produtos
POST http://localhost:3000/
Content-Type: application/json

{
    "id": 3,
    "nome": "Mouse",
    "preco": 25,
    "quantidade": 10

}

###

### editar produtos
PUT http://localhost:3000/1
Content-Type: application/json

{
    "novoNome": "Monitor 30 editado",
    "novoPreco": 4500,
    "novaQuantidade": 2

}

###

### Remover produtos
DELETE http://localhost:3000/1
Content-Type: application/json

###